### ISSUE TITLE
[WP 5.9] Block editor crash when saving posts with Statuses module

### ISSUE THREAD

**Issue by dkoo** [publishpress/PublishPress#1000]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Clicking "Save" on a draft post should save the post.

## Current Behavior

When saving a draft post with the Statuses module active, the block editor crashes like so:

<img width="861" alt="Screen Shot 2022-01-26 at 3 19 36 PM" src="https://user-images.githubusercontent.com/2230142/151256698-ca96a69a-6915-4aea-90b7-120bc8400de5.png">

The JS console shows this error on crash:

```
DOMException: Node.insertBefore: Child to insert before is not a child of this node
```

## Possible Solution

This may or may not be related to WordPress 5.9. I mention it because a client started reporting it only after their site was updated to the new version in the past 24 hours.

## Steps to Reproduce (for bugs)

1. On a site using WordPress 5.9 and PublishPress with the Statuses module enabled, create a new post.
2. Save the post as a draft.
3. Observe the editor crash as described above.

## Your Environment

* Version used: WordPress 5.9; PublishPress Pro v3.0.3
* Browser Name and version: Any
* Operating System and version (desktop or mobile): MacOS

**Comment by stevejburge** [comment]
Closing this because it's a report for version 3.0.3. Updating a new version will solve this.
