### ISSUE TITLE
Error is getting displayed when user will try to clicking on post/page editor.

### ISSUE THREAD

**Issue by nayana96249** [publishpress/PublishPress#1003]
Error is getting displayed when the user will try to click on post/page editor.

## Current Behavior

-> Update WP 5.9 version.
-> Go to the page/post editor.
-> See the error log.

## Your Environment

WP-5.9 

Screenshot :

<img width="1433" alt="Screenshot 2022-02-01 at 7 19 35 PM" src="https://user-images.githubusercontent.com/51028940/151980593-d18f90a3-c481-4194-9b5a-eec627810bd8.png">

**Comment by stevejburge** [comment]
@nayana96249 Sorry this is the wrong Github repo and the problem will be solved if you update the plugin.

**Comment by nayana96249** [comment]
Thanks for the quick response.
