### ISSUE TITLE
Deprecated: WP_User_Query was called with an argument that is deprecated, on WP 5.9

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#1014]
PHP deprecated error in the Notifications metabox while editing a post logged in as a "contributor" user.

```
Deprecated: WP_User_Query was called with an argument that is <strong>deprecated</strong> 
since version 5.9.0! <code>who</code> is deprecated. Use <code>capability</code> instead.
 in /www/kinsta/public/plugindev/wp-includes/functions.php on line 5600
```

![image](https://user-images.githubusercontent.com/407131/155037715-921355ab-4a1c-48dd-a2cd-165a59101ef1.png)

**Comment by stevejburge** [comment]
One more report of this, logged in as an admin
![Uploading Screen Shot 2022-03-14 at 6.19.47 PM.png…]()
