### ISSUE TITLE
Slack notifications referencing slack users by raw member IDs stopped working after v3.7.1

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#1042]
Slack supports mentioning users on messages referencing the using "@<username>". But in the API, it requires using the member ID, specially because some users have spaces in the name, breaking the syntax.

Adding something like `@UAFBFS503` should show the notification to the user as a mention. But the update v3.7.1 broke that feature.

Slack's API requires wrapping that member ID mention using `< >` chars, like `<@UAFBFS503>`. PublishPress was detecting the member IDs on messages (using Regex) and wrapping them with the `< >` chars. But after the update, it stopped doing that.

**Comment by andergmartins** [comment]
This is probably related to the usage of a deprecated filter `publishpress_slack_text`, which was renamed to `publishpress_slack_message_text`.

When Slack messages are sent I'm receiving the following error:

```
Deprecated: Hook publishpress_slack_text is <strong>deprecated</strong> since version 3.7.2! Use publishpress_slack_message_text instead. in /www/kinsta/public/plugindev/wp-includes/functions.php on line 5754
```

Fixing the filter name in the call `add_filter('publishpress_slack_text', [$this, 'filter_slack_text']);` fixes the deprecated error log, but I'm not sure would fix the issue on Slack, making it recognize the user mentions.

**Comment by andergmartins** [comment]
If a user has issues right now, you can instruct them to manually wrap the user id like `<@UA83459>`.

**Comment by olatechpro** [comment]
Thanks for the full explanation @andergmartins, it makes identifying the issue easier.
