### ISSUE TITLE
Rename the plugin to "PublishPress Planner"

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#1077]
@stevejburge We have been talking about maybe renaming the plugin from "PublishPress" to "PublishPress Workflows", "PublishPress Calendars", etc.

I would like to suggest renaming it to "PublishPress Hub". This is a shorter name, and considering this plugin has the potential to be the hub for all the other plugins we have, the name probably makes that clearer.

It would not be required for the other plugins, but could be used to integrate all them using flexible custom workflows if we implement it like suggested on #805.

Considering custom workflows/integrations can lead to more support requests, they should only be available in the Pro plugin, leaving only the current notification workflows on the free plugin. Limited options for integrated notifications would be available in the free plugins. And more flexible ones in the pro. 

On both free and pro versions, "Publishpress Hub" makes it clear it can aggregate info (in the calendar view, content overview, notifications...) and notifications for our plugins.

**Comment by stevejburge** [comment]
Thumbs up from me @andergmartins 

I'd been kicking around ideas like "PublishPress Dashboard"

This is definitely the future direction for this plugin.

**Comment by andergmartins** [comment]
Another idea: "PublishPress Flow"

**Comment by stevejburge** [comment]
"PublishPress Schedule"

**Comment by stevejburge** [comment]
@olatechpro Not yet. I'll put this to the team and we'll decide in the next few days
