### ISSUE TITLE
Double slug on page draft mode

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress#1087]
ISSUE: Double slug on page draft mode

Step to replicate:
1. Create page A
2. Publish
3. Create page B
4. Set page attributes -> Parent page into page A
5. Save as draft
6. Observe issue, it will give you a double slug
![image](https://user-images.githubusercontent.com/83811723/182875141-edcbac97-32d2-40b4-afde-67f786d53f0b.png)

This issue disappear if you either publish it or deactivate PublishPress plugin

**Comment by olatechpro** [comment]
@stevejburge Is there PublishPress issue here?

**Comment by rizaardiyanto1412** [comment]
@olatechpro Yes this issue arise when PublishPress (Editorial Calendar) was activated. It was from this support thread: https://wordpress.org/support/topic/when-post-in-draft-permalink-have-double-parent-in-url/

**Comment by olatechpro** [comment]
Okay, will check @rizaardiyanto1412
