### ISSUE TITLE
Notification User Role Keeps Reverting

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress#1136]
Step to replicate:
1. Go to Notification
2. Edit one of the notification
3. Select the user to specific user, e.g: contributor
![image](https://user-images.githubusercontent.com/83811723/195900750-246055e8-cfb9-4395-964b-6028684f08d0.png)

4. Click Update
5. Observe issue, it select all user instead: 
![image](https://user-images.githubusercontent.com/83811723/195900829-57bdd0b9-661e-4e48-9a06-b6a9e16276d6.png)

This issue only happens on 3.8.4. Works fine on previous version

**Comment by SeaBoot** [comment]
Can confirm this behavior.
