### ISSUE TITLE
PPRESS-307 ⁃ Page for listing editorial comments with links to the articles

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#119]
> How can I list all editorial notes in one page with links to the posts where are they origin?
> 
> Because now I get email that someone of my editors made a note in post XYZ but it is complicated to looking them. I looking for some simple list like for comments: https://www.suenee.cz/wp-admin/edit-comments.php. I think this is the best way it could be working.
> 

#### Support topic
https://wordpress.org/support/topic/list-all-editorial-notes/#post-9889103

**Comment by stevejburge** [comment]
One  more vote for this today
