### ISSUE TITLE
Text changes for 3.10

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#1190]
Add to Post Types
This metadata will be available for these post types.

Viewable
If enabled, this metadata can be seen outside of the post editing screen.

Show on Post Types screen
This metadata will be viewable on the overview screens for these post types.

Show as Content Overview filters
If enabled, this metadata will be available as filter option on the Content Overview screen.

Show on Content Calendar form
If enabled, this metadata will be available when adding new posts on the Content Calendar screen.
 
<img width="1112" alt="Screen Shot 2022-11-23 at 11 01 15 AM" src="https://user-images.githubusercontent.com/3868028/203530687-a9065f60-aaf8-432f-8507-6c0d292c74ae.png">

**Comment by olatechpro** [comment]
@stevejburge On 
` Enable term in the selected post types column. <<< **I'm not sure what this means**

The implementation was to fix this issue https://github.com/publishpress/PublishPress/issues/464

Does that help in creating description?
`

**Comment by stevejburge** [comment]
@olatechpro OK, thanks. I've updated the text details above

Should the settings under "Viewable" be hidden if it is set to "No"?

**Comment by olatechpro** [comment]
I think so. I'll check and update

**Comment by olatechpro** [comment]
@stevejburge After checking viewable usage, it's also one of the settings that determine metadata filters that shows in Content Overview screen as well as calendar that's not post type dependent.

I'm wondering if we just need better description for this or should really remove it meaning all metadata will automatically show on Content Overview filter area?

**Comment by stevejburge** [comment]
@olatechpro Yes, please. We do need a better description. Is this correct?

"If enabled, this metadata can be seen on the Content Calendar and Content Overview screens."

**Comment by olatechpro** [comment]
Make sense @stevejburge
