### ISSUE TITLE
Date filter on Content Overview

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#1192]
We allow "Date" fields to be added as a filter to Content Overview, but it's not clear how to use them:

<img width="1388" alt="Screen Shot 2022-11-25 at 9 33 06 AM" src="https://user-images.githubusercontent.com/3868028/203947815-00cb5754-6fb6-485b-be11-4683c47687de.png">

**Comment by olatechpro** [comment]
@stevejburge If you're referring to the date filter in "Content overview starting....." as in https://github.com/publishpress/PublishPress/issues/1194, that's not a field or metadata filter but content overview screen date filter that allow to limit posts/cpt between post published on the specified range.

So, it's not a metadata filter added to the screen but a static settings for when post is published.

So, if that's what you mean, what's the new proposal or changes?

**Comment by stevejburge** [comment]
@olatechpro This is a First Draft Date field
<img width="1211" alt="Screen Shot 2022-11-25 at 9 50 27 AM" src="https://user-images.githubusercontent.com/3868028/203953142-cf016a5e-ecaa-4f9c-a91d-63e34c053949.png">

**Comment by olatechpro** [comment]
Okay, you want this to be date picker for easy understanding? @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Yes, I wonder what the best approach is. A date picker will only allow one date. Is a date range possible?

**Comment by olatechpro** [comment]
Okay, I'll check what's possible. @stevejburge

**Comment by olatechpro** [comment]
Okay, I'll check what's possible but with date range, that shows we'll be providing two input. @stevejburge

**Comment by stevejburge** [comment]
Thanks @olatechpro
