### ISSUE TITLE
Text filter not working on Content Overview

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#1193]
In my testing, I can't search for Assignment keywords:
<img width="1398" alt="Screen Shot 2022-11-25 at 9 38 28 AM" src="https://user-images.githubusercontent.com/3868028/203951615-37fd90d1-9063-49f9-b412-e3008d2f5408.png">

**Comment by olatechpro** [comment]
@stevejburge The attached image wasn't uploaded

**Comment by stevejburge** [comment]
@olatechpro Sorry, moving too quickly

**Comment by olatechpro** [comment]
Got it now @stevejburge
