### ISSUE TITLE
Remove extra row on Metadata table headers

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#1195]
Can we remove the double row caused by these headings?

Maybe we can remove these columns and have a "Post Types" row using the "Add to post types" column
<img width="726" alt="Screen Shot 2022-11-25 at 10 03 35 AM" src="https://user-images.githubusercontent.com/3868028/203956901-b02b777f-51b8-4c89-b9b9-6de2cfe05e37.png">

**Comment by olatechpro** [comment]
@stevejburge, we already have a "Post Types" column which shows the post types the metadata is attached to(based on our previous conversation). So, won't using same title be for Add to post types column be confusing or we should remove that one?

**Comment by stevejburge** [comment]
@olatechpro Sorry, my bad. We can just remove those two columns
