### ISSUE TITLE
Allow moving posts to future and not visible dates

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#165]
We should be able to move a post to the end of the month, year, etc... even if the date is not visible right now in the calendar. When moving, display a drop area for moving to future, asking the date.

#### Support ticket (private)
https://secure.helpscout.net/conversation/536932600/65181/

**Comment by stevejburge** [comment]
Closed in favor of https://github.com/publishpress/PublishPress/issues/339
