### ISSUE TITLE
Calendar Doesn't Refresh

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#174]
If you add multiple items to one date, the Calendar screen operates correctly and hides some of them using "Show 5 more"

However, if you move some items to a different date, the Calendar still hides those items ...

!calendar-doesnt-refresh.png|thumbnail!

┆Attachments: <a href="https:&#x2F;&#x2F;ostraining.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;20210&#x2F;calendar-doesnt-refresh.png">calendar-doesnt-refresh.png</a>

**Comment by OSTraining** [comment]
➤ Steve Burge commented:

This happens with Published / Scheduled content also ...

1) An item appears as "Published" on the Calendar
2) Drag it to a future date. It still appears as "Published"

It's only when you refresh the Calendar that it changes to "Scheduled", which is the expected behavior.

**Comment by andergmartins** [comment]
This was fixed on the new async calendar. Can't replicate this anymore.
