### ISSUE TITLE
Add support for "unclaimed" posts. Undefined author

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#192]
I am looking for a way to put "unclaimed" pitches on the calendar so that authors who want to write on those can claim them.

#### Support ticket (private)
https://secure.helpscout.net/conversation/543004082/65651?folderId=898239

**Comment by stevejburge** [comment]
I wonder if there's a way to do this with Multiple Authors? "Unclaimed" could be a fake / guest author

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/publishpress/PublishPress/issues/278
