### ISSUE TITLE
Add option to hide the Notify metabox for authors

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#199]
The option should be set by Role.

### Support tickets
https://secure.helpscout.net/conversation/566678734/67806?folderId=898239
https://secure.helpscout.net/conversation/1067391721/112266?folderId=2557470

**Comment by stevejburge** [comment]
Also related: https://github.com/OSTraining/PublishPress/issues/198

**Comment by andergmartins** [comment]
Note to self: Before adding the metabox we already look for the capability `edit_post_subscriptions`.
