### ISSUE TITLE
Add support for Guest Author avatars

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#239]
> We are adding Guest Authors who, not being mapped authors or even WordPress users, do not have Gravitar acccounts. The whole point of Guest Authors is to display guest author info without their needing to even be WP users. So how can we integrate images for them without having to create/setup/confirm Gravitar accounts? As we do want to display/link their email addresses on the bylines without making them go through Gravitar account confirmation, the Gravitar business seems especially problematic.

**Comment by Arne-Pfeilsticker** [comment]
I would also appreciate user-independent guest authors with their own avatar.

My workaround is the plugin WP User Avatar. You then have to create a guest author as a user, but then you can assign a picture as an avatar from the media library.

**Comment by stevejburge** [comment]
Thumbs up from me. We'll try and add this in the next release of PublishPress

**Comment by heyjoecampbell** [comment]
Hey @stevejburge was this feature added?

**Comment by stevejburge** [comment]
@heyjoecampbell Great to hear from you. Yes, this was solved earlier in 2019. I'll close this issue
