### ISSUE TITLE
Filter from MultipleAuthors overrides core function with wrong post count

### ISSUE THREAD

**Issue by daniel-lohse** [publishpress/PublishPress#250]
The filter `add_filter( 'get_authornumposts', [ $this, 'filter_count_author_posts' ], 10, 2 );`
on line 83 located in file  **"/publishpress-multiple-authors/publishpress-multiple-authors.php"**
which calls `filter_count_author_posts( $count, $term_id )` overrides the count_user_posts() wp core  function with wrong post counts!

The function gets the wrong $term_id, thats why the returned query result don't match the post_author ID and the wp core post count gets overwritten by the wrong value.

If you run this you can check how many posts exist for a term_taxonomy_id and match it with your users post count
`SELECT term_taxonomy_id, COUNT(Id)`
`FROM wp_posts AS p`
`INNER JOIN wp_term_relationships AS tr ON (tr.object_id = p.ID)`
`WHERE p.post_status NOT IN ('trash', 'auto-draft')`
`GROUP BY term_taxonomy_id;`

**Comment by andergmartins** [comment]
Hi @pioneerLohse please, could you try again using the following beta package?

http://packages-tmp.s3.amazonaws.com/905aac7d37117dc267d9f2f5d18e8228/publishpress-multiple-authors-2.1.1-beta.3.zip

Thanks

**Comment by daniel-lohse** [comment]
Hey, just saw that the count_user_posts() still returns wrong vales - after research I found out the get_by_user() function in Author class still returning other term_id than the author of the post really has.

**Comment by daniel-lohse** [comment]
Hey @andergmartin, you have any new discoveries on this topic or some hints you can give me for fixing it?

**Comment by andergmartins** [comment]
I'm closing this because the discussion was moved to publishpress/publishpress-authors#17.
