### ISSUE TITLE
Notification box is only half-width

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#255]
![screen shot 2018-07-02 at 11 30 47 am](https://user-images.githubusercontent.com/3868028/42172894-6b82b5a4-7deb-11e8-8dcc-5dd8c16d0187.png)

**Comment by andergmartins** [comment]
I can't reproduce this anyore. Maybe it is not a valid bug anymore?

**Comment by stevejburge** [comment]
@andergmartins Agreed. We can close this one
