### ISSUE TITLE
Need to be able to edit or delete Editorial Comments

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#277]
> Editorial comments are fantastic and we use them all the time. However, it just doesn't make sense that comments can't be edited or deleted. Creating any kind of content that can never be changed is just a recipe for complaints. Every member of my team has asked how they can edit or delete comments, and every member of my team is confused and unwilling to accept the answer when I say it isn't possible. And so I pass that feedback on to you.

**Comment by stevejburge** [comment]
One more vote for this today

**Comment by jenniferlynparsons** [comment]
I just started using this plugin and am already getting requests from my editors for this feature.

**Comment by stevejburge** [comment]
One more request for this today

**Comment by seemaprabhu** [comment]
Also getting requests for this!

**Comment by stevejburge** [comment]
Agreed. "Edit" and "Delete" buttons do seem like worthwhile additions here.

**Comment by yannikbauer** [comment]
Dear developer team,
I would strongly second the need for "edit" and "delete" buttons. We have just started using the Plugin and notice that old resolved editorial comments keep piling up in the admin space of our pages without us being able to remove them. Do you have any updates on when you can roll out the feature?

**Comment by stevejburge** [comment]
Hi @yannikbauer We've got a public roadmap for 2019 https://publishpress.com/blog/roadmap/

But we would like to squeeze this feature into a 2019 release too

**Comment by yannikbauer** [comment]
Great, thanks for your quick reply @stevejburge! Very much looking forward to the release as PublishPress is a great tool that we would love to continue to use. Thanks again for all your work!

**Comment by stevejburge** [comment]
One more request for this today

**Comment by stevejburge** [comment]
One request to integrate this with permissions:

> Ability to edit / delete the Editorial Comments (should respect permissions, e.g. Admin can edit all, but others can only edit their own)

**Comment by andergmartins** [comment]
One more request for this
