### ISSUE TITLE
include the post content in the email notifications

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#288]
This is a good idea from a customer:

> include the post content in the email notifications

**Comment by stevejburge** [comment]
One request for this feature on WordPress.org https://wordpress.org/support/topic/psppno_post-content/

**Comment by qaziatif786** [comment]
I need the same functionality to include post content into the notifiocation. but there is not any option but to directly edit the plugin.

It would be great if you can provide this functionality in next update 

simply edit the Notifications/Shortcodes.php file 
and add 3 lines of code after line 363

```
		case 'content':
                $info[] = $post->post_content;
                break;
```

Thank you

**Comment by andergmartins** [comment]
Thanks for the contribution @qaziatif786
