### ISSUE TITLE
Multiple Authors does not turn on despite being active in Gutenberg

### ISSUE THREAD

**Issue by neddonovan13** [publishpress/PublishPress#307]
I have "Multiple Authors" selected from the General Settings, yet in the post (I use Gutenberg 4.4) there is no ability to select Multiple Authors

**Comment by andergmartins** [comment]
Hi @neddonovan13 thank you for reporting this issue. I can confirm it. We are working on the Gutenberg compatibility, and will publish more information soon. But feel free to report any other issue you find. 

Thanks
