### ISSUE TITLE
404 while loading assets in backend

### ISSUE THREAD

**Issue by tschortsch** [publishpress/PublishPress#315]
Hi. I'm using the latest version of the plugin (1.17.0) and I'm getting lots of 404s while the plugin is trying to load its assets in the backend.
![publishpress-assets](https://user-images.githubusercontent.com/1061850/49426440-e09cca80-f7a0-11e8-9d23-0c28a0085e23.png)

It seems like the `wordpress-plugin-framework` dependency loads the assets with an absolute path of the server `/var/www/content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/assets/css/allex-grid.min.css?ver=0.4.11` and adds the website url (`https://mywebsite.org/cms`) in front of it `https://mywebsite.org/cms/var/www/content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/assets/css/allex-grid.min.css?ver=0.4.11`.

This seems to come from this constant in `wordpress-plugin-framework/src/library/Module/Assets.php`: `$this->container['ASSETS_BASE_URL']` which again gets the absolute path from `$c['FRAMEWORK_BASE_PATH']`.

Am I doing something wrong? Do I need to configure this somewhere?
Thanks a lot!

**Comment by stevejburge** [comment]
Solved in 1.20.0
