### ISSUE TITLE
Wrong cursor in the remove button for existent authors in the metabox

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#326]
In the metabox, when hovering the delete button for existent authors the cursor should be a pointer. It is displaying the 4-way cross.

**Comment by htmgarcia** [comment]
@andergmartins this has been fixed at some point. When hovering the "X", the cursor is a pointer.
![Screen Shot 2021-11-02 at 10 15 45](https://user-images.githubusercontent.com/4999794/139902837-3afd920e-3b1d-4aa1-a8f4-c0dcdac9c46b.png)
