### ISSUE TITLE
Stop loading assets on non-PublishPress /wp-admin/ pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#330]
Currently we're loading CSS and JS on non-PublishPress /wp-admin/ pages

**Comment by stevejburge** [comment]
@andergmartins This is a key issue in a lot of bug reports.

For examples, here's PublishPress causing trouble in the customizer ...

![unnamed](https://user-images.githubusercontent.com/3868028/58494859-05686e00-8144-11e9-8cf7-da4d5621eff8.jpg)
.

**Comment by stevejburge** [comment]
> I've noticed two things when PublishPress enqueues its scripts and styles:
> 
Customer feedback:

> 1. They appear to be enqueued globally in the dashboard area, rather than only enqueued when needed on PublishPress admin pages. I believe the latter is considered "best practice" for WP plugins
> 
> 2. The way they are enqueued does not account for systems where theme and plugin files live outside the WP folder structure and are referenced by symlink. For example, for git purposes, on my development VM I've symlinked my plugins directory to /media/sf_prime/plugins/. That means your plugin tries to enqueue scripts and styles like this:
> example.local/wp-content/media/sf_prime/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/assets/css/allex-admin.css?ver=0.6.0

**Comment by andergmartins** [comment]
Another report:

> Using the Calendar Plugin we found that it conflicted with another plugin and had to uninstall until this is addressed - here's the message from WP RSS Aggregator:
> "Thanks, we can confirm the issue on our test machines.
> 
> However, we've found the issue to be emerging from PublishPress. They happen to be using a JavaScript library that we are using as well, called ChosenJS, for enhancing searchable dropdown menus.
> 
> The PublishPress plugin is loading the ChosenJS library on WP RSS Aggregator's Edit Feed Source page. Hence, you will need to request PublishPress' developers to load the ChosenJS library only on pages where they need it."
