### ISSUE TITLE
Change the PublishPress icon to a calendar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#338]
This old icon isn't helping:

<img width="155" alt="screen shot 2019-01-31 at 10 37 47 am" src="https://user-images.githubusercontent.com/3868028/52065316-43fa6d00-2544-11e9-821f-f764df0cb440.png">

**Comment by Daniel-Pickering** [comment]
View this email in your browser (https://mailchi.mp/ostraining/javascript-explained?e=8687404db5)
https://www.ostraining.com/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781

Hey everyone,

If you use WordPress in a professional way, you've probably come across Zac Gordon.

Zac is an enthusiastic and charming teacher who focuses on Javascript in WordPress. He borrowed the phrase "Learn Javascript Deeply" from Matt Mullenweg and he made it into his personal slogan. For the last several years, Zac has produced video classes, online conferences, live talks, and podcasts that focus on teaching you how to use Javascript in WordPress.

We recently partnered with Zac on a book, "React Explained (books/react/) ". That book is available now. It's a fun and enjoyable introduction to React, which is the Javascript framework of choice for WordPress, Drupal, Magento, and thousands of developers.

React Explained was a great project, so we're delighted to announce that our collaboration is continuing.

Zac is working on a second book, "Javascript Explained".
More about Javascript Explained (https://www.ostraining.com/blog/news/javascript-explained/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
https://www.ostraining.com/blog/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781


** New Gutenberg tutorials
------------------------------------------------------------

Over the last few weeks, I've been using (and enjoying) Gutenberg more and more.

I've learned to work around its eccentricities and in many way it has made my blogging faster and easier. The Reusable blocks feature has been particularly useful (https://www.ostraining.com/blog/wordpress/how-to-reuse-blocks/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781) . I'm able to create an image with a caption, or a list of useful links, and quickly drop it into any post.

Gutenberg 5.5 introduces a new "Group" block (https://www.ostraining.com/blog/wordpress/group-block/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)  which is about the make Reusable blocks even better.

This month, we also expanded the WordPress beginner class with new videos, including a guide to image galleries in Gutenberg (https://www.ostraining.com/class/wp-beginner/image-galleries/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781) .

Finally, we wrote about several ways to extend Gutenberg:
* Google Drive blocks (https://www.ostraining.com/blog/wordpress/google-docs-wordpress/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
* Twitch.tv video blocks (https://www.ostraining.com/blog/wordpress/twitch-gutenberg/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
* Wistia video blocks (https://www.ostraining.com/blog/wordpress/wistia-gutenberg/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)

https://www.ostraining.com/podcast/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781


** New OSTraining Podcast episodes
------------------------------------------------------------
Two new podcast episodes dropped recently.

Episode #38 (https://www.ostraining.com/blog/podcasting/zac-gordon/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781) featured Zac Gordon. I just introduced Zac earlier in the newsletter so won't do that again here. I talk with Zac about his background, his love of yoga, and also about why he decided to focus on React for his first book.

Episode #39 (https://www.ostraining.com/blog/podcasting/april/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781) featured April Sides, a Drupal developer who works for Lullabot, one of the biggest and most reputable Drupal agencies. She's worked on all sorts of fascinating projects, and at the moment she's helping Georgia.gov (the state of Georgia), move many of their Drupal sites over to Drupal 8. We talk about what she's been doing in the Drupal world, about DrupalCon Seattle, which happened the previous week. Plus, what we discuss being part of a massive government project and helping people out by making government websites easier to use and easier to search
See all the OSTraining podcasts (https://www.ostraining.com/podcast/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
If you want to talk or send any feedback, you can just click reply, or email me via steve@ostraining.com (mailto:steve@ostraining.com) .
Steve Burge

============================================================

OSTraining PO Box 110264 Bradenton, Florida 34211 United States
** update your preferences (https://ostraining.us1.list-manage.com/profile?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=8687404db5)
| ** unsubscribe from this list (https://ostraining.us1.list-manage.com/unsubscribe?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=8687404db5&c=4a7a57b687)
** (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
** Facebook (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
** (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
** Twitter (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
** (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)
** YouTube (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272023781)

**Comment by Daniel-Pickering** [comment]
View this email in your browser (https://mailchi.mp/ostraining/star-war-sale?e=8687404db5)
https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781
https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781


** Star Wars Day Sale!
Join OSTraining for only $54 for 1 year!
------------------------------------------------------------

This is one of the most epic discounts we've ever offered at OSTraining.

Star Wars Day is May 4th every year ... "May the force" ... "May the fourth" ... say it a few times and you'll get it!

For Star Wars Day, you can get 1 year of access to everything in OSTraining for only $54!
* Join today and you'll save $90!
* Enjoy WordPress, Drupal, Magento, Joomla, Coding, Marketing and SEO video classes ... plus lots more!
* You can download our complete library of ebooks. This includes new books "React Explained" and "CSS Grid Explained", plus upcoming books, "Javascript Explained", "Flexbox Explained" and "Bootstrap 4 Explained".

Join OSTraining today for only $54 (https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
If you have any questions at all, you can just click reply, or email me via steve@ostraining.com (mailto:steve@ostraining.com) .
Steve Burge

============================================================

OSTraining PO Box 110264 Bradenton, Florida 34211 United States
** update your preferences (https://ostraining.us1.list-manage.com/profile?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=8687404db5)
| ** unsubscribe from this list (https://ostraining.us1.list-manage.com/unsubscribe?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=8687404db5&c=8088ee7218)
** (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
** Facebook (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
** (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
** Twitter (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
** (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
** YouTube (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272023781)
