### ISSUE TITLE
Quick Edit doesn't support Multiple Authors yet

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#350]
We don't yet have support for multiple authors in the "Quick Edit" dropdown
<img width="513" alt="screen shot 2019-02-08 at 8 54 31 am" src="https://user-images.githubusercontent.com/3868028/52482395-29954480-2b7f-11e9-854b-a8b845cfb489.png">

**Comment by andergmartins** [comment]
This field is hidden for now, until we are able to implement support for Multiple Authors
