### ISSUE TITLE
New notification trigger: post is assigned

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#358]
Customer:

> Add new trigger when the Editor associates a Post to a Contributor, or a Contributor gets a Post for him.

**Comment by jorr** [comment]
@stevejburge I believe this echoes my comment in https://github.com/publishpress/PublishPress/issues/344

the attached patch can be used to solve this ;)

**Comment by stevejburge** [comment]
Wonderful, thanks @jorr. I'll close this in favor of that ticket
