### ISSUE TITLE
Default statuses are broken

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#362]
Choose a default status. For example, "Assigned":

<img width="669" alt="screen shot 2019-02-20 at 12 41 20 pm" src="https://user-images.githubusercontent.com/3868028/53112292-e2a73780-350c-11e9-9fa0-3395077e2e03.png">

That's not reflected in the post editor:

<img width="329" alt="screen shot 2019-02-20 at 12 42 19 pm" src="https://user-images.githubusercontent.com/3868028/53112333-fc487f00-350c-11e9-8edd-bb73c7af8d51.png">

**Comment by andergmartins** [comment]
This is only happening on the block editor
