### ISSUE TITLE
Block the ability to delete Draft and Pending Review statuses

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#363]
We seem to confuse Gutenberg if we allow people to delete "Draft" and "Pending Review" statuses.

It's not a super-serious issue, but it's a UI issue at least.

The solution may be to stop people from deleting those two statuses.

![test](https://user-images.githubusercontent.com/3868028/53199452-1fe2f680-35ed-11e9-9bf1-e5ac8c2fb7b3.png)

**Comment by stevejburge** [comment]
One user reported using a "Sweep" plugin that deleted the status.

Perhaps we could add a "reset" option to restore the default statuses.

**Comment by andergmartins** [comment]
Related to the issue #311

**Comment by andergmartins** [comment]
Fixed on #311
