### ISSUE TITLE
Too many content types breaks Statuses setting sreen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#372]
Need a UI fix here:

<img width="874" alt="screen shot 2019-03-06 at 7 07 01 am" src="https://user-images.githubusercontent.com/3868028/53881320-63703400-3fe1-11e9-81a3-d61a0d8bf29b.png">

**Comment by jorr** [comment]
@stevejburge I believe this is a duplicate for #342 - I am still to open a PR based on my patch that solves this but maybe you can close this one :)

**Comment by stevejburge** [comment]
You're correct, thanks @jorr 

Closing in favor of https://github.com/publishpress/PublishPress/issues/342
