### ISSUE TITLE
WSOD for Notifications because of terms trashing

### ISSUE THREAD

**Issue by jphorn** [publishpress/PublishPress#375]
I'm am revisiting PublishPress again for our multi author site after previously toying with it in our test environment (and contributing some issues here).

We want to use PublishPress (and its commercial add-ons, which I have to renew again) mostly for the (Slack) notifications feature, but exactly this feature is what causing consistently a WSOD ("White Screen of Death") for us.

`Allowed memory size of 268435456 bytes exhausted`

According to my freelance developer @stayallive this is because PublishPress' Notifications feature is trying to load all terms (e.g. tags or Yoast prominent keywords or other taxonomies) to let users use them for filters. This makes sense of course, but doesn't work for high volume sites with thousand of posts. We have over 32.500 posts alone, not counting all custom post types. Because our site is over 10 years old, we accumulated also many many (post) tags (over 3200, although we try to prune). PublishPress tries to load all these tags at once in the interface in this code segment in `PublishPress\Notifications\Workflow\Step\Event_Content\Filter\Term` ([link](https://github.com/publishpress/PublishPress/blob/2304461394d25fd6fba02b03c192e43d6b48f64f/libraries/Notifications/Workflow/Step/Event_Content/Filter/Term.php))
```php
$terms = get_terms(['hide_empty' => false]);
```
Unfortunately this isn't filterable, so right now we're unable to use PublishPress :-( Could you please reconsider this implementation?

Maybe you cold use [FakerPress](https://nl.wordpress.org/plugins/fakerpress/) or similar tools to mimic large datasets to test with?

**Comment by stevejburge** [comment]
Thanks @jphorn. Perhaps the best solution could be a setting to remove this option for large sites?

**Comment by jphorn** [comment]
Setting or filter would be great. A slightly less user friendly approach would be to just let users input any taxonomy manually instead of preloading them.

**Comment by stayallive** [comment]
I think adding a filter to set the taxonomies to load (or which not to load) would be a good solution since Yoast is our biggest issue. 

```sql
SELECT taxonomy, count(*) as tax_count FROM wp_term_taxonomy GROUP BY taxonomy ORDER BY tax_count DESC;
```

The query above results in:

```
yst_prominent_words	220517
post_tag	        3289
// ... <the rest all below 100>
```

So maybe even adding a blacklist for `yst_prominent_words` would be sufficient since I don't think anyone is ever going to filter based on that tax? But a filter to configure that would be nice since we would have a few more internal taxes to exclude.

**Comment by stevejburge** [comment]
On more report of this today

**Comment by Daniel-Pickering** [comment]
View this email in your browser (https://mailchi.mp/ostraining/javascript-explained?e=c3793781c7)
https://www.ostraining.com/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377

Hey everyone,

If you use WordPress in a professional way, you've probably come across Zac Gordon.

Zac is an enthusiastic and charming teacher who focuses on Javascript in WordPress. He borrowed the phrase "Learn Javascript Deeply" from Matt Mullenweg and he made it into his personal slogan. For the last several years, Zac has produced video classes, online conferences, live talks, and podcasts that focus on teaching you how to use Javascript in WordPress.

We recently partnered with Zac on a book, "React Explained (books/react/) ". That book is available now. It's a fun and enjoyable introduction to React, which is the Javascript framework of choice for WordPress, Drupal, Magento, and thousands of developers.

React Explained was a great project, so we're delighted to announce that our collaboration is continuing.

Zac is working on a second book, "Javascript Explained".
More about Javascript Explained (https://www.ostraining.com/blog/news/javascript-explained/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
https://www.ostraining.com/blog/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377


** New Gutenberg tutorials
------------------------------------------------------------

Over the last few weeks, I've been using (and enjoying) Gutenberg more and more.

I've learned to work around its eccentricities and in many way it has made my blogging faster and easier. The Reusable blocks feature has been particularly useful (https://www.ostraining.com/blog/wordpress/how-to-reuse-blocks/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377) . I'm able to create an image with a caption, or a list of useful links, and quickly drop it into any post.

Gutenberg 5.5 introduces a new "Group" block (https://www.ostraining.com/blog/wordpress/group-block/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)  which is about the make Reusable blocks even better.

This month, we also expanded the WordPress beginner class with new videos, including a guide to image galleries in Gutenberg (https://www.ostraining.com/class/wp-beginner/image-galleries/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377) .

Finally, we wrote about several ways to extend Gutenberg:
* Google Drive blocks (https://www.ostraining.com/blog/wordpress/google-docs-wordpress/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
* Twitch.tv video blocks (https://www.ostraining.com/blog/wordpress/twitch-gutenberg/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
* Wistia video blocks (https://www.ostraining.com/blog/wordpress/wistia-gutenberg/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)

https://www.ostraining.com/podcast/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377


** New OSTraining Podcast episodes
------------------------------------------------------------
Two new podcast episodes dropped recently.

Episode #38 (https://www.ostraining.com/blog/podcasting/zac-gordon/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377) featured Zac Gordon. I just introduced Zac earlier in the newsletter so won't do that again here. I talk with Zac about his background, his love of yoga, and also about why he decided to focus on React for his first book.

Episode #39 (https://www.ostraining.com/blog/podcasting/april/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377) featured April Sides, a Drupal developer who works for Lullabot, one of the biggest and most reputable Drupal agencies. She's worked on all sorts of fascinating projects, and at the moment she's helping Georgia.gov (the state of Georgia), move many of their Drupal sites over to Drupal 8. We talk about what she's been doing in the Drupal world, about DrupalCon Seattle, which happened the previous week. Plus, what we discuss being part of a massive government project and helping people out by making government websites easier to use and easier to search
See all the OSTraining podcasts (https://www.ostraining.com/podcast/?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
If you want to talk or send any feedback, you can just click reply, or email me via steve@ostraining.com (mailto:steve@ostraining.com) .
Steve Burge

============================================================

OSTraining PO Box 110264 Bradenton, Florida 34211 United States
** update your preferences (https://ostraining.us1.list-manage.com/profile?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=c3793781c7)
| ** unsubscribe from this list (https://ostraining.us1.list-manage.com/unsubscribe?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=c3793781c7&c=4a7a57b687)
** (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
** Facebook (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
** (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
** Twitter (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
** (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)
** YouTube (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=4a7a57b687-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-4a7a57b687-272028377)

**Comment by Daniel-Pickering** [comment]
View this email in your browser (https://mailchi.mp/ostraining/star-war-sale?e=c3793781c7)
https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377
https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377


** Star Wars Day Sale!
Join OSTraining for only $54 for 1 year!
------------------------------------------------------------

This is one of the most epic discounts we've ever offered at OSTraining.

Star Wars Day is May 4th every year ... "May the force" ... "May the fourth" ... say it a few times and you'll get it!

For Star Wars Day, you can get 1 year of access to everything in OSTraining for only $54!
* Join today and you'll save $90!
* Enjoy WordPress, Drupal, Magento, Joomla, Coding, Marketing and SEO video classes ... plus lots more!
* You can download our complete library of ebooks. This includes new books "React Explained" and "CSS Grid Explained", plus upcoming books, "Javascript Explained", "Flexbox Explained" and "Bootstrap 4 Explained".

Join OSTraining today for only $54 (https://www.ostraining.com/star-wars-day-sale/?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
If you have any questions at all, you can just click reply, or email me via steve@ostraining.com (mailto:steve@ostraining.com) .
Steve Burge

============================================================

OSTraining PO Box 110264 Bradenton, Florida 34211 United States
** update your preferences (https://ostraining.us1.list-manage.com/profile?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=c3793781c7)
| ** unsubscribe from this list (https://ostraining.us1.list-manage.com/unsubscribe?u=c4fe34ed80790dd773846d4e1&id=d282df070a&e=c3793781c7&c=8088ee7218)
** (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
** Facebook (https://www.facebook.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
** (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
** Twitter (https://twitter.com/ostraining?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
** (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)
** YouTube (https://www.youtube.com/user/ostrainingcom?utm_source=OSTraining&utm_campaign=8088ee7218-EMAIL_CAMPAIGN_2018_08_16_06_31_COPY_01&utm_medium=email&utm_term=0_d282df070a-8088ee7218-272028377)

**Comment by stevejburge** [comment]
@jphorn Can you check if this new settings resolves the problem?

<img width="555" alt="Screen Shot 2019-05-06 at 9 58 38 AM" src="https://user-images.githubusercontent.com/3868028/57230092-8de06c80-6fe5-11e9-8211-4126f5c32cf2.png">

**Comment by jphorn** [comment]
I tried adding `yst_prominent_words` to the list of Blacklisted taxonomies (since that's by far our biggest taxonomy), but I'm still getting WSOD for the Notifications configuration. Is `yst_prominent_words` the correct slug? I'm not sure what input is expected for this input field?

**Comment by stevejburge** [comment]
Thanks for testing that @jphorn - you were doing it right. Sorry it didn't work. 

Are there any error messages shown or recorded in logs after the WSOD?

**Comment by jphorn** [comment]
This is all relevant in my php-error.log (MAMP Pro/macOS)
```log
[07-May-2019 17:14:44 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /Users/jphorn/Sites/iculture.dev/wp-includes/wp-db.php on line 1972
[07-May-2019 17:14:44 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 159744 bytes) in /Users/jphorn/Sites/iculture.dev/wp-includes/functions.php on line 4212
[07-May-2019 17:14:44 UTC] PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

**Comment by stevejburge** [comment]
Thanks. We'll look again and figure this out

**Comment by jphorn** [comment]
Thanks to WordPress 5.2 Site Health feature I got this email just now with additional debugging. Hope it helps.
```Error Details
=============
An error of type E_ERROR was caused in line 83 of the file /private/var/www/iculture/wp-content/plugins/publishpress/libraries/Notifications/Workflow/Step/Event_Content/Filter/Term.php. Error message: Uncaught Error: Cannot pass parameter 1 by reference in /private/var/www/iculture/wp-content/plugins/publishpress/libraries/Notifications/Workflow/Step/Event_Content/Filter/Term.php:83
Stack trace:
#0 /private/var/www/iculture/wp-content/plugins/publishpress/libraries/Notifications/Workflow/Step/Event_Content/Filter/Term.php(32): PublishPress\Notifications\Workflow\Step\Event_Content\Filter\Term->get_options()
#1 /private/var/www/iculture/wp-content/plugins/publishpress/vendor/twig/twig/src/Template.php(671): PublishPress\Notifications\Workflow\Step\Event_Content\Filter\Term->render()
#2 /private/var/www/iculture/wp-content/plugins/publishpress/vendor/twig/twig/src/Environment.php(497) : eval()'d code(79): Twig\Template->getAttribute(Object(PublishPress\Notifications\Workflow\Step\Event_Content\Filter\Term), 'render', Array, 'method')
#3 /private/var/www/iculture/wp-content/plugins/publishpress/vendor/twig/twig/src/Template.php(427): __TwigTemplate_ab4d73a4e5667965929cca8993950cbdf930bda9f7618301d68ca09d55258```

**Comment by stayallive** [comment]
I opened a PR (#423) with a solutions that seems to work correctly.

**Comment by stevejburge** [comment]
A huge thank you from us, @stayallive. We'll take a close look at your PR and make sure this problem gets solved.

**Comment by jphorn** [comment]
Confirming this is now indeed solved in our test environment after installing PublishPress v1.20.5.

**Comment by stevejburge** [comment]
That's great to hear. Thanks @jphorn and thanks also @stayallive
