### ISSUE TITLE
Add or change the author in the popup window in the calendar

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#38]
> Add a field for the author. This is specially important for sites where one person add drafts and assign to other editors

**Comment by stevejburge** [comment]
We have a patch for this thanks to @jorr

@deenison Could you take a look?
[0001-Joro-PublishPress-1.18.0-Calendar-Allow-setting-auth.patch.zip](https://github.com/publishpress/PublishPress/files/2841759/0001-Joro-PublishPress-1.18.0-Calendar-Allow-setting-auth.patch.zip)

**Comment by deenison** [comment]
sure thing @stevejburge, the PR was [sent](https://github.com/publishpress/PublishPress/pull/371). @jorr patch looks good!

I've just tweaked the code a bit patching a minor permission potential-issue.

Thanks again @jorr 
Cheers
