### ISSUE TITLE
Display publication time in the calendar

### ISSUE THREAD

**Issue by OSTraining** [publishpress/PublishPress#39]
One user wants the option to show the time on the calendar screen

**Comment by stevejburge** [comment]
One more request for this today:

> 
> in the calendar is it possible to immediately show the time of publication as in the Editorial Calendar plugin (https://wordpress.org/plugins/editorial-calendar/)?
> This is somewhat important to our site since we publish once an hour and it is important to keep this under the eye.

**Comment by stevejburge** [comment]
>  It's currently 11:47am but if I want to schedule something for 6pm tonight I have to go into the post to change the time. It feels like this should be doable (as is standard in other calendar plugins) from the calendar.
