### ISSUE TITLE
Calendar shows 2 different times for one items

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#422]
One item has 2 dates that are 5 hours apart:

<img width="327" alt="Screen Shot 2019-05-08 at 2 04 21 PM" src="https://user-images.githubusercontent.com/3868028/57397235-3cc5a980-719a-11e9-955f-7722bd9733d4.png">

10.24 is the correct publishing time as shown on the "Edit Post" screen.

**Comment by stevejburge** [comment]
From a user:

> Here's the view for a Scheduled post in the PP Calendar, which you'll see for 2pm ET (note, i don't see the publish time within the pop-up):

![edit-post-page](https://user-images.githubusercontent.com/3868028/57402306-05a8c580-71a5-11e9-8c8a-8c366fe54bc4.jpg)

> Here's the view for a Scheduled post in the PP Calendar, which you'll see for 2pm ET (note, i don't see the publish time within the pop-up):

![schedule](https://user-images.githubusercontent.com/3868028/57402321-0e010080-71a5-11e9-8570-20bcc6e5168a.jpg)

**Comment by deenison** [comment]
Perhaps the same as #415

**Comment by stevejburge** [comment]
@deenison Thanks - yes, I think so. Could we find a solution for this? It's a key problem with the time feature still

**Comment by deenison** [comment]
Absolutely @stevejburge, thanks. The fix is already committed and should be published on the next update, later today or tomorrow.
