### ISSUE TITLE
PHP error messages reported by Siteground

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#436]
Siteground is telling users not to run PublishPress because of these errors:

FILE: /wp-content/plugins/publishpress/vendor/twig/twig/src/Extension/CoreExtension.php
—————————————————————————————————————–
FOUND 1 ERROR AFFECTING 1 LINE
—————————————————————————————————————–
1184 | ERROR | The function mb_ord() is not present in PHP version 7.1 or earlier
—————————————————————————————————————–

FILE: /wp-content/plugins/publishpress/publishpress.php
————————————————————————————————————
FOUND 2 ERRORS AFFECTING 2 LINES
————————————————————————————————————
111 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
494 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

**Comment by andergmartins** [comment]
Twig seems to have a fallback for mb_ord, if it is not defined. But Siteground is probably only finding the function name in the code and is triggering the warning as an error, when that code is probably not executed. 

```
if (function_exists('mb_ord')) {
    function twig_ord($string)
    {
        return mb_ord($string, 'UTF-8');
    }
} else {
    function twig_ord($string)
    {
        $code = ($string = unpack('C*', substr($string, 0, 4))) ? $string[1] : 0;
        if (0xF0 <= $code) {
            return (($code - 0xF0) << 18) + (($string[2] - 0x80) << 12) + (($string[3] - 0x80) << 6) + $string[4] - 0x80;
        }
        if (0xE0 <= $code) {
            return (($code - 0xE0) << 12) + (($string[2] - 0x80) << 6) + $string[3] - 0x80;
        }
        if (0xC0 <= $code) {
            return (($code - 0xC0) << 6) + $string[2] - 0x80;
        }

        return $code;
    }
}
```

**Comment by andergmartins** [comment]
I can add the `polyfil-mbstring` library as a requirement, making mb_ord available on servers when mb_ord does not exists. In fact, that is what the most recent releases of Twig is doing, requiring `symfony/polyfill-mbstring`.

But if Siteground is showing that warning after parse the file instead of running it, that wouldn't work. I will add the polyfill and send a package for the user to test.

**Comment by andergmartins** [comment]
I reverted the commit which added the Polyfill-mbstring library because Twig already have a fallback and Siteground whitelisted the plugin based on it. So we only need the fix for the call-time pass-by-reference issue, which was merged into the development branch.
