### ISSUE TITLE
Notifications catches too many items from WooCommerce

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#440]
PublishPress still catches some things that are not Post types:

> If you use the PublishPress plugin your admin email account will be flooded with 'wc_admin_unsnooze_admin_notes' and 'wc-admin_import_order' email messages - thousands of them. It took me an hour to clean up my inbox.

https://wordpress.org/support/topic/terrible-plugin-doesnt-play-with-woocommerce-partial-orders-or-publishpress/

**Comment by stevejburge** [comment]
@andergmartins Some feedback on that post:

> Unfortunately, the PublishPress “notify when content is published” workflow indiscriminately sends emails for all post types. It seems that you’ll receive emails for any post type that transitions status, including DB updates performed by WooCommerce as well as WooCommerce Admin historical imports.
> 
> I believe this filter will stop notification on older version of PublishPress: add_filter( 'pp_notification_scheduled-action_status_change', '__return_false' );, but the latest version uses a different mechanism with no straightforward way to hook into.
> 
> While WooCommerce Admin’s usage of Action Scheduler (which is what caused this) is quite extensive, this “bug” looks like it can occur with any plugin that uses custom post types. This will ultimately need to be resolved in the PublishPress plugin.
>

**Comment by jeffstieler** [comment]
Please let me know if I can help resolve this!

**Comment by stevejburge** [comment]
Thanks @jeffstieler. I hope we'll find time to tackle this bug this week

**Comment by stevejburge** [comment]
From another user:

> I installed the free version of PublishPress, and now I receive a flow of email notifications. I would like to know what setting to turn off? The email message is
> "wc_admin_unsnooze_admin_notes" was published

We really need to get on this one

**Comment by stevejburge** [comment]
From another user, the problem comes from these:

wc_square_sync
wc_admin_unsnooze_admin_notes

**Comment by andergmartins** [comment]
I just added a check making sure we only run a notification workflow for supported post types.

**Comment by andergmartins** [comment]
For those having this issue we have a new beta package planned for releasing next week:

https://github.com/publishpress/PublishPress/releases/tag/1.20.9-beta.3

You are welcome to test it. Thanks
