### ISSUE TITLE
Publish Date behaves differently for custom statuses

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#478]
From a user:

> When I add a post as "draft", the publish date is set to "Publish: immediately". If I use your custom statuses, the date is set as soon as I save the fist time. (e.g.:"Publish on: Aug 23, 2019 @ 13:31") Is there any way to avoid this? (Because it adds an extra step of work for the editor who publishes the post in the end, to update the date)

Here's the default WordPress behavior: Draft and "Immediately"

![Screen Shot 2019-08-23 at 9 53 51 AM](https://user-images.githubusercontent.com/3868028/63597632-f1d67300-c58b-11e9-8029-1122ae15a596.png)

Here's the date with a custom status:

![Screen Shot 2019-08-23 at 9 53 02 AM](https://user-images.githubusercontent.com/3868028/63597690-0ca8e780-c58c-11e9-9903-54bc1bc5ad3d.png)

**Comment by andergmartins** [comment]
Closing this in favor of #546 .
