### ISSUE TITLE
Store a log of notifications, sent or scheduled

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#500]
We need a better for debugging notification issues. Right now it runs completely in the background, making it very hard to debug. 

We should keep a log of all the scheduled or sent/unsent notifications with the proper sending status.

On the log we need to know:

* Notification Workflow
* The event
* Post that triggered the event
* Filters
* Receivers
* Channel
* Datetime
* Status log (when it was created, sent, canceled, pending, scheduled, etc)
* Error message

**Comment by andergmartins** [comment]
Log is a passive component in the system, so we are considering the option to create a Queue for notifications instead.

**Comment by andergmartins** [comment]
We are going to implement a queue instead of a simple log, but we still can display the sent/scheduled notifications inside a post.

**Comment by stevejburge** [comment]
Solved with 1.21.0
