### ISSUE TITLE
Allow to create public post statuses

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#505]
Client's request:

>We've created a custom status called "Updated", the purpose of which is to show that a post has not only been published, but updated since publication
the issue we're having is that it seems none of the PP post statuses are public, so it's effectively a draft and only viewable from the dashboard

>is there a way to make, essentially, a status that function as second "Published" status, complete with update button (instead of publish)

Right now all the custom post statuses are created as protected. We could give the option to configure that allowing to set them as public.
Check "public" and options here: https://codex.wordpress.org/Function_Reference/register_post_status

This would maybe require to customize the Publish Button allowing to publish to this specific status.

**Comment by andergmartins** [comment]
There is a chance this fits better on Revisionary. We are checking...

**Comment by stevejburge** [comment]
Yes, my thinking is it would be a better Revisionary feature https://github.com/publishpress/Revisionary/issues/17
