### ISSUE TITLE
Slack Notifications broken for new posts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#510]
Create a new post and this is what Slack sends:
![Screen Shot 2019-10-08 at 12 34 36 PM](https://user-images.githubusercontent.com/3868028/66414794-182f6100-e9c8-11e9-9679-e4975ef4493d.png)

**Comment by stevejburge** [comment]
Possibly related to this? https://github.com/publishpress/PublishPress/issues/418

**Comment by stevejburge** [comment]
Maybe not as as this just happened when moving from Draft to Live:
![Screen Shot 2019-10-08 at 1 17 47 PM](https://user-images.githubusercontent.com/3868028/66417498-19638c80-e9ce-11e9-9f11-aab7175d2dbe.png)

**Comment by andergmartins** [comment]
I was able to replicate this issue when Async notifications is enabled. I can see in the notifications log that the notification is scheduled with the correct text. But the log related to the message sent is broken. Only for post status changes using the Full theme.
