### ISSUE TITLE
Scheduled column in Notification log

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#523]
We updated this but it's still not 100% right.

"scheduled in the cron" can be confusing for people. And in some cases, it shows next to a green checkmark:

<img width="397" alt="Screen Shot 2019-10-23 at 11 37 12 AM" src="https://user-images.githubusercontent.com/3868028/67410057-7db74c00-f589-11e9-89c1-9462fd5abf8b.png">

**Comment by andergmartins** [comment]
Fixed this implementing a new log table and other changes in the notifications handling.
<img width="1074" alt="Screen Shot 2020-06-11 at 16 59 15" src="https://user-images.githubusercontent.com/407131/84433621-f3e5ed00-ac04-11ea-8dac-8db42c603a09.png">
