### ISSUE TITLE
string(2) "no" following upgrade

### ISSUE THREAD

**Issue by jclwilson** [publishpress/PublishPress#526]
## Expected Behavior

Plugin should work following an upgrade from `1.20.9` to `1.21.0`.

## Current Behavior

While PublishPress is activated, all admin pages return only the plaintext `string(2) "no"`.

The front end of the site remains unaffected.

## Steps to Reproduce (for bugs)

Upgrade from `1.20.9` to `1.21.0` using the inbuilt WordPress upgrade tool. The issue begins immediately, and only when viewing admin pages.

I verified the plugin checksums using `WP CLI` which confirmed there were no errors.

To be certain, I reinstalled the plugin from scratch using the `WP CLI` plugin installer and the issue persists.

The issue is resolved by deactivating PublishPress or downgrading to version `1.20.9`.

## Your Environment

* Version used: `1.21.0`
* Server Operating System and version: `Ubuntu Bionic`
* Kernel: `Linux 4.15.18`
* PHP: `7.2.23`

**Comment by stevejburge** [comment]
Thanks for reporting that @jclwilson. Version 1.21.1 is out with a fix. 

This was a hard bug to track down. It only occurred for people who had clicked one option on the "Please review us" box that shows for PublishPress
