### ISSUE TITLE
Editorial comments sorted incorrectly

### ISSUE THREAD

**Issue by jclwilson** [publishpress/PublishPress#536]
## Expected Behavior

Editorial comments should be sorted chronologically.

## Current Behavior

Editorial comments are sorted incorrectly, the latest comment, left on 11/02/2019, is displayed at the bottom of the list. See image below.

![Screenshot_2019-11-01_14-00-57](https://user-images.githubusercontent.com/3199935/68029882-1cd9f300-fcb0-11e9-8f1a-ac33488157b2.png)

## Possible Solution

I imagine it's caused by our site using `DD/MM/YYYY` formatting opposed to `MM/DD/YYYY`, while the plugin still uses the latter.

## Your Environment

- Version used: 1.21.0
- Server Operating System and version: Ubuntu Bionic
- Kernel: Linux 4.15.18
- PHP: 7.2.23

**Comment by stevejburge** [comment]
Thanks for reporting @jclwilson
