### ISSUE TITLE
Priority issue with callbacks for notifications

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#545]
> Seems to be some priority level issue with callbacks. The message callback seems to occur before DB save.
> 
> If I use metadata fields in email, if I don't do a save before state change, the metadata won't appear in email.
> 
> Say I have field 1 I'm using in message - if I enter info for field 1 in post editor and do a save as 'current state', then change state, I get info in my message.
> 
> If i enter info for field 1 in post editor and do a publish (or state change) which does a save, my message won't have the info.

**Comment by andergmartins** [comment]
This was fixed a few months ago: 2fcf2abdb911d47bdc448189a908876ed209e9c6
