### ISSUE TITLE
Incorrect Publish Times

### ISSUE THREAD

**Issue by Kpudlo** [publishpress/PublishPress#546]
## Expected Behavior

Since the update to WP 5.3 we've been noticing that posts are saving with publish date in drafts instead of still showing `publish immediately`.

## Current Behavior

Posts and drafts are saving with publish dates instead of staying blank.

## Possible Solution

[Changes to WP 5.3 regarding PHP sound like they could be the issue.](https://wordpress.org/support/topic/read-this-first-wordpress-5-3-master-list/#post-12124062)

## Steps to Reproduce (for bugs)

1. Install WP 5.3 and the latest PublishPress
2. Create a new post
3. Save as draft

## Context

It's really messed up our writing team with having posts publish at times earlier than what they should've. Additionally it's caused some haywire functionality with our Zapier integrations, and has not triggered some zap's that should've

## Your Environment

* Version used: WP 5.3, PublishPress 1.21.2
* Multiple systems, browsers, and authors
* Was able to reproduce using Gutenberg and Classic Editor

![image](https://user-images.githubusercontent.com/4432822/69472862-59fc4700-0d7d-11ea-8cc6-2659e7fc74ac.png)

**Comment by stevejburge** [comment]
Thanks for such a detailed report @Kpudlo. We'll take a close look this week

**Comment by andergmartins** [comment]
Hi @Kpudlo I tried following the steps you listed here, but I wasn't able to reproduce the bug.
Please, could you double check using this demo server? Can you replicate the issue there?

Username: demo
Password: Sz0Ei94oLZv4
URL for this demo: http://embarrassed-gentoo.w6.wpsandbox.pro

Here are 2 screencasts of my tests using classic editor and Gutenberg.
Am I missing anything?

I see a bug in the "Save as" label, and it seems like using Gutenberg, the demo site set a publishing date if you set any state different than Draft.

Classic Editor:
https://youtu.be/0VO6katePZU

Gutenberg:
https://youtu.be/YXd9KxwEqug

**Comment by Kpudlo** [comment]
Hi @andergmartins! Thank you for looking into this so quickly! I watched your videos, and did try on the test site, and I was getting the same results as you. 

However, after a second post with Class Editor, I noticed that it does occur, but not like I've encountered on my Flywheel Local install. When I save a post as another step in the process (pitch, assigned, etc) and then save it back to draft, I was able to replicate
![image](https://user-images.githubusercontent.com/4432822/69681210-5ddce180-107b-11ea-88b8-71001a324f2d.png)

I then went back to try this in Gutenberg and found something interesting. The publish time is changing whenever I switch post statuses' but is reverting back to immediately when I switch to draft.
https://youtu.be/uhsLD6Cjn_c

**Comment by Kpudlo** [comment]
Hi @andergmartins, 

I was checking in to see if you've been able to replicate this at all after my last feedback?

**Comment by andergmartins** [comment]
Hi @Kpudlo sorry for the delay. 

Thank you for the details. I can reproduce the issue on both classic and block editor. 
I'm still working to find a fix. It seems like the custom statuses different from Draft are treated by WP as "publish"

**Comment by andergmartins** [comment]
Note to self: Check the filter_insert_post_data method in the custom-status module. The methods wp_insert_post and wp_update_post set the post_date_gmt if the status is different then 'draft', 'pending' or 'auto-draft'. There is no way to change that behavior.

wp-includes/post.php:4178

```
// Drafts shouldn't be assigned a date unless explicitly done so by the user.
	if ( isset( $post['post_status'] ) && in_array( $post['post_status'], array( 'draft', 'pending', 'auto-draft' ) ) && empty( $postarr['edit_date'] ) &&
			( '0000-00-00 00:00:00' == $post['post_date_gmt'] ) ) {
		$clear_date = true;
	} else {
		$clear_date = false;
	}
```

and wp-includes/post.php:3731

```
if ( empty( $postarr['post_date_gmt'] ) || '0000-00-00 00:00:00' == $postarr['post_date_gmt'] ) {
		if ( ! in_array( $post_status, get_post_stati( array( 'date_floating' => true ) ), true ) ) {
			$post_date_gmt = get_gmt_from_date( $post_date );
		} else {
			$post_date_gmt = '0000-00-00 00:00:00';
		}
	} else {
		$post_date_gmt = $postarr['post_date_gmt'];
	}
```

We already have a partial fix here: wp-content/plugins/publishpress/modules/custom-status/custom-status.php:2381

```
if (!in_array($data['post_status'], ['publish', 'future'])) {
                // Check if the dates are the same, indicating they were auto-set.
                if ($data['post_date'] === $data['post_date_gmt'] && $data['post_modified'] === $data['post_date']) {
                    // Reset the date
                    $data['post_date_gmt'] = '0000-00-00 00:00:00';
                }
            }
```

But it is not working on all the cases

**Comment by Kpudlo** [comment]
@andergmartins I tested this the other day using Edit Flow, and that one did seem to be working OK with 5.3, maybe there is something in their code that might be helpful?

**Comment by stevejburge** [comment]
I believe we just had one more customer report of this:

> With PublishPress installed, the story is assigned, written, saved as a draft, edited and then published. The last step takes place several hours after the story is assigned, yet the publish time appears as the time it was actually assigned and isn't changing to reflect the actual time.
> 
> I just checked on our staging site. After deactivating PublishPress, the publish time and date don't appear when I save a story as Draft. The time and date only appear after the post has been published and the time is shown correctly.
> 
> On the live site, the date and time appear as soon as I save a post as Assigned or Draft.

**Comment by andergmartins** [comment]
I'm testing a workaround for this. I can't stop WordPress to automatically set the publish date if the status is different than draft, pending, publish or scheduled. And when a post is saved, I can't know if the date was saved by the user by purpose or by WordPress. So I'm proposing we force to update the publish date every time the post is published, using the current date. 

The only caveat for now seems to be If a post is scheduled to the future and WP miss the publish date for a while. When the time comes and WP publishes the post, we will update the publish time again, creating a publish date a little different from the scheduled one. But if this probe to be a real problem, we can try to find a workaround... maybe comparing the previous state before publishing. If scheduled, we skip the initial workaround.

**Comment by andergmartins** [comment]
Here is an alpha package for testing the fix:

https://www.dropbox.com/s/8g8xzca2sipct57/publishpress-2.0.4-alpha.2.zip?dl=0

**Comment by Kpudlo** [comment]
@andergmartins I tried the alpha and things seemed to work as intended, thanks! I'll work on getting some more testing done with and without Gutenberg!

**Comment by andergmartins** [comment]
Hi @Kpudlo Cool, thanks for confirming the fix. We have a new alpha package improving the fix, to avoid updating the publish date when a published post is edited. Few free to test it:

https://www.dropbox.com/s/osog84ndwnbvyt1/publishpress-2.0.4-alpha.3.zip?dl=0

**Comment by andergmartins** [comment]
We received many reports about duplicated posts.
Basically, after publishing a post that was in a custom status the post was duplicated. One published and the other in the old status.

**Comment by andergmartins** [comment]
The problem was that I changed the action I was hooking from "publish_post" to "transition_post_status" which receive different arguments. The bug is being caused because I didn't refactor one variable, the $id. So that variable is found as undefined, and a new post is created since the id is empty.

**Comment by iamkingsleyf** [comment]
I imported 500+ articles via CLI guess what? they all have the new date which is today instead of maintaining its original date.
Thanks guys -_-

**Comment by andergmartins** [comment]
Sorry for the inconvenience @iamkingsleyf we will release the fix for this on the next version.
