### ISSUE TITLE
Can't publish a post with retrospective date. The publish date is always updated to the current date. 

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#603]
Some users may want to publish posts with retrospective publish date. But we added a code to always update the publish date after publishing to fix the bug #546.

**Comment by jorr** [comment]
Quick comment here - I believe the behaviour introduced by the fix is the correct one. Posts can always be updated (as opposed to "published") with a retrospective date (I was able to do this before the fix as well).

**Comment by andergmartins** [comment]
Right, thank you @jorr for the feedback and for checking the option to update the post. That makes sense. I'm closing this for now.
