### ISSUE TITLE
Notifications workflows edit page takes too much time to load when there are thousand of users or taxonomies in the site

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#622]
The filter fields don't use ajax requests, loading and rendering all the data set every time you load the page. This is a problem for sites with thousands of users, or thousand of taxonomies, mainly. We should refactor those fields to load the data using Ajax instead, so the data set size won't be a problem. 

I had to temporarily disable the taxonomies field for a client because he has about 30000 taxonomies being rendered in the field and the page was taking about 2 minutes to load.

**Comment by CodingSamurai** [comment]
We have the same problem.  In addition to have 50,000 taxonomies we also have 150,000 users.  In addition beyond just editing the workflow this also affects the Notifications metabox on post/page editing.
