### ISSUE TITLE
400 error for admin-addons.min.js.map; causing conflict with Dashboard on WordPress VIP Go

### ISSUE THREAD

**Issue by ckoerner** [publishpress/PublishPress#628]
## Expected Behavior
Enable PublishPress plugin and no conflict. Resources load as needed.

## Current Behavior

Enabling PublishPress causing issues with Widget management (wp-admin/widgets.php) and other plugin admin interfaces. CSS and JS are not loading properly. Can not reproduce on local VVV environment, only on "live" development site hosted by WordPress VIP Go.

## Possible Solution

When enabling the PublishPress plugin we get an error message in the console.

[Error] Failed to load resource: the server responded with a status of 400 () (admin-addons.min.js.map;, line 0)

This works as intended on local instances and appears to be something to do with how VIP Go hosts static assets. The file is present in the development repo, but when viewing on the develop site is loaded from _static and throws an 400 error (Bad Request). 

The file is located at: publishpress/vendor/alledia/wordpress-plugin-framework/src/assets/js/admin-addons.min.js.map

## Context

I have a request in for support from VIP as I _think_ this is more on their side, but wanted to inform the authors of PublishPress. I'm sure I'm not the only one using PublishPress on VIP. :) 

In my limited troubleshooting the only other instance I could find that is remotely related is: https://github.com/publishpress/PublishPress/issues/336

## Your Environment

* Version used: 2.1.0
* Browser Name and version: Safari 13.1, Chrome, Firefox
* Operating System and version (desktop or mobile): N/A
* Link to your project: https://blog-wikimedia-org-develop.go-vip.net (but no public access to admin, where the issue is appearing)

**Comment by stevejburge** [comment]
Thanks for the detailed feedback @ckoerner. We've issues with PublishPress Revisions also that are unique to VIP.  I'd love to hear more if their team reply.

**Comment by ckoerner** [comment]
Coming back to this. Our agreement with VIP only provides in-depth code and theme review for the code we created. Third-party plugins only get a PHP CodeSniffer review. Ive extinguished the resources I have at hand and instead am working around the issue by deactivating PublishPress when I need to interact with parts of the Dashboard. I've attached the report in hopes it might be beneficial to you all. 

[phpcs report.zip](https://github.com/publishpress/PublishPress/files/4928300/phpcs.report.zip)

**Comment by ckoerner** [comment]
A small update. Since I reported this the widget interface is now working as intended. Still getting a 400 error on the admin-addons.min.js.map file. PublishPress is at now at version 2.2.1 and WordPress at 5.5.1

**Comment by stevejburge** [comment]
Thanks @ckoerner. We have no access to look at this, unfortunately. Do the VIP team have any thoughts?

**Comment by ckoerner** [comment]
I think I have figured out the issue here. I've been working with VIP on some issues I've been experiencing related to a few plugins not working correctly from the administration side of things. Visitors to the site are seeing functionality working just fine, but like the few issues shared here with you all (#644, #645), the admin interface is having hiccups.

Automattic uses [a WordPress plugin](https://github.com/Automattic/nginx-http-concat) to concatenate JS and CSS files. From the very helpful VIP support person who is helping me, "When scripts are concatenated, some of them include a "use strict"; requirement, as seen in this admin-addons.min.js file. This requirement is then inherited by any JS which is concatenated afterwards, some of which do not meet strict JS standards. This can cause a variety of errors, as you've seen here."

You can use query strings to temporarily disable concatenation (?concat_js=no) or provide a filter in your functions.php to disable. Doing so alleviates the error reported here. I was also able to verify that it fixes the issue described in #645.

**Comment by stevejburge** [comment]
Awesome, thanks @ckoerner. That's super helpful

**Comment by andergmartins** [comment]
@ckoerner Please, could you try again usgin the version we released yesterday? The most recent released do not require the "wordpress-plugin-framework" package anymore, so the error related to admin-addons.min.js.map should be fixed.
