### ISSUE TITLE
Configure button in block editor "Advanced panels" showing unescaped text

### ISSUE THREAD

**Issue by ckoerner** [publishpress/PublishPress#631]
![Screen Shot 2020-06-09 at 4 29 40 PM](https://user-images.githubusercontent.com/232862/84323012-9afe5200-ab3b-11ea-9e4d-791d5ce7ca21.png)

## Expected Behavior

When viewing the "More tools & options>Options" menu in the WordPress block editor (found in the top right three dot menu next to "Publish" and the "Settings" gear icon. All the way at the bottom is a link to "Options"). Under "Advanced panels" there are options to show or hide panels related to plugins, including Editorial Metadata and Editorial Comments. Users should be able to see the human text label. 

## Current Behavior

When viewing the "More tools & options>Options" menu in the WordPress block editor (found in the top right three dot menu next to "Publish" and the "Settings" gear icon. All the way at the bottom is a link to "Options"). Under "Advanced panels" there are options to show or hide panels related to plugins, including Editorial Metadata and Editorial Comments. Users should be able to see the human text label. There is text that should not be appearing, appearing. :)

## Possible Solution

It looks like there's a missing tag somewhere in the code. 

## Steps to Reproduce (for bugs)

1. Install WordPress
2. Enable PublishPress
3. Go to add a new post
4. Click on "More tools & options" then "Options"
5. Scroll to the "Advanced panels" section. 
6. See screenshot. :)

## Your Environment

* Version used: PublishPress 2.1.0, WordPress 5.4.1

**Comment by stevejburge** [comment]
Thanks @ckoerner
