### ISSUE TITLE
Double statuses

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#633]
This only happens if a site has been upgraded from an earlier version
![Screen Shot 2020-06-11 at 9 26 02 AM](https://user-images.githubusercontent.com/3868028/84392386-510f7d80-abc8-11ea-83ec-0e99903e5341.png)

**Comment by andergmartins** [comment]
@stevejburge I can't reproduce this one. Please, could you try again using this package?

[publishpress-2.2.0-beta.1.zip](https://github.com/publishpress/PublishPress/files/4782545/publishpress-2.2.0-beta.1.zip)

**Comment by stevejburge** [comment]
@andergmartins I can't recreate again. We can close for now
