### ISSUE TITLE
Upgrade to Pro link breaks with Capabilities installed

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#634]
If you have PublishPress Capabilities installed, the "Upgrade to Pro" disappears:

![Screen Shot 2020-06-11 at 9 54 59 AM](https://user-images.githubusercontent.com/3868028/84393538-b4e67600-abc9-11ea-9839-4d117bdd7e75.png)

**Comment by agapetry** [comment]
@andergmartins I've committed the vendor library update to PP Capabilities and released as 1.9.11

Regarding the development branch, I have been in the habit of creating version-specific development branches instead.

**Comment by andergmartins** [comment]
Thanks @agapetry. Sounds good.
