### ISSUE TITLE
Improve permission control to edit editorial metadata fields in the post

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#655]
Before allowing to edit editorial metadata fields in the post we apply the filter `pp_editorial_metadata_user_can_edit`. If it returns true we allow to edit, otherwise the field is only in read-only mode.

It would be better to look for specific capability, so that behavior could be easily controlled using PublishPress Permissions for example.

The capability could be called: `pp_edit_editorial_metadata`

**Comment by olatechpro** [comment]
This issues has been fixed `pp_edit_editorial_metadata`
