### ISSUE TITLE
Uncaught TypeError: $(...).live is not a function

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#657]
The .live function is deprecated since jQuery 1.7.

WordPress 5.5 updated jQuery to 1.12.4 and the function is now removed.

**Comment by vulieumang** [comment]
I had same issue,
I had fix by install plugin "https://wordpress.org/plugins/enable-jquery-migrate-helper/"
you can try
https://wordpress.org/support/topic/javascript-error-on-version-5-5/

**Comment by andergmartins** [comment]
Thanks @vulieumang we are planning a release for fixing this issue.
