### ISSUE TITLE
Add Metadata top level menu link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#666]
This is very similar to the changes for statuses:
https://github.com/publishpress/PublishPress/issues/620

- Make Metadata a top-level link
- Redesign the screen so Post Types are on the first level

**Comment by olatechpro** [comment]
@stevejburge can you explain the second issue better?

> "Redesign the screen so Post Types are on the first level"

**Comment by stevejburge** [comment]
Thanks @olatechpro 

So we'll move this screen to the Main Menu. Inside each metadata item, can we choose the post type it applies to?

![Screen Shot 2022-11-03 at 3 00 46 PM](https://user-images.githubusercontent.com/3868028/199811087-4a56d6d9-1f28-4900-90cc-9046db775d63.png)
