### ISSUE TITLE
Error: selected user doesn't have enough permissions to be set as the post author

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress#704]
The calendar's popup to create posts displays users without permission to be authors.
Before creating the post we check if the user has the capability "edit_posts". The filter "publishpress_author_can_edit_posts" is applied after that verification.

We need to properly filter the field to only display users who can be authors, or the authors listed in the Authors plugin.

**Comment by jorr** [comment]
@andergmartins the description doesn't seem to cover my case correctly (this occured to me after the last update).
This happens with **all normal author** users who most certainly have permission to be authors. The problem is not that you don't filter the field properly but rather that maybe a wrong permission check is being made.

**Comment by andergmartins** [comment]
Hi @jorr you are right. I didn't test enough when I created the issue here. 
Testing again I see the problem is related to the permission check, because the unique way to not get that error message is adding a Guest Author as author in the post. So it fails for any author mapped to user. Working on that 👍  thanks for the contribution.

**Comment by andergmartins** [comment]
I see the problem in the code. It is calling the method `$user->can()` what is not a valid call. It should be `$user->has_cap()`. But I see other problems related to the integration with the Authors plugin. Fixing it.

**Comment by jorr** [comment]
awesome, good work as usual :)

**Comment by andergmartins** [comment]
Thanks @jorr
