### ISSUE TITLE
Some broken shortcodes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#713]
These two shortcodes product a blank result in notifications:

```
[psppno_edcomment url] 
[psppno_edcomment ip] 
```

We can either fix or remove them.

**Comment by stevejburge** [comment]
One more:

[psppno_receiver name]

This produces the email address of the receiver, not their name

**Comment by stevejburge** [comment]
Some more broken statuses:

[psppno_post old_status]

**Comment by andergmartins** [comment]
More broken shortcodes:

`[psppno_post old_status]`
`[psppno_post new_status]`

**Comment by andergmartins** [comment]
> These two shortcodes product a blank result in notifications:
> 
> ```
> [psppno_edcomment url] 
> [psppno_edcomment ip] 
> ```
> 
> We can either fix or remove them.

The shortcode `[psppno_edcomment url] is invalid, we should use [psppno_edcomment author_url]` instead. I just updated the doc page.

**Comment by andergmartins** [comment]
> , not their name

The shortcode `[psppno_receiver name]` will display the "display_name" property of the user. Not the First name + Second name, for example.
