### ISSUE TITLE
Add a setting to toggle reset of publishing date

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#715]
Related to https://github.com/publishpress/PublishPress/issues/546 https://github.com/publishpress/PublishPress/issues/603

> I'm unable to backdate my posts after installing this plugin. If I set it to a date and time in the past, the date and time will update to the date and time of publishing. I do not find any settings for turning this off. Clearly, this must be a bug?

> I often publish articles with drink recipes. These recipes are published as individual posts so that it's possible to display the recipes in grids elsewhere on the page.
> Publishing a post with 10 recipes means backdating these 10 posts so that they do not show up under recent posts and are not included in the weekly newsletter containing this week's new posts.
> After doing this, I then link up these 10 posts in a post titled, i.e. 10 drinks for Halloween.
> The way PublishPress is working now means that these 10 recipes will briefly show up as the newest posts on the website and that I have to open 10 posts and manually set the publishing date.

> The above example, and the fact that it is changing the native Worpress behaviour, as you also point out in your guide, in my view, warrants an option to turn this off in Settings.

**Comment by andergmartins** [comment]
Maybe this won't be needed anymore. I'm checking the fix sent for the issue #741 .
