### ISSUE TITLE
Persistent Filters on Content Overview

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#739]
> is there a way to make the filters persistent in the post and page lists in wp-admin? The filters work fine, but if I edit and save a post/page, I have to re-select the filter. When you're working on or creating multiple items in a specific category, the lack of persistent filters is highly unproductive.

**Comment by stevejburge** [comment]
> The default order in which posts are displayed is the newest at the bottom which means I always have to scroll to find the ones I am working on or click the up arrow and wait. How about remembering the last order I used to view the list??

**Comment by andergmartins** [comment]
Note to self: check `PP_Content_Overview::handle_form_date_range_change`.

**Comment by olatechpro** [comment]
@stevejburge, these are the filter you're talking about right and the request is to remember last selected options for all filters drop down ?

I'm trying to understand the refering to this "...is there a way to make the filters persistent in the post and page lists in wp-admin?" just incase it's refering to post/page creation/edit page 

![content-overview](https://user-images.githubusercontent.com/46832636/142678147-794b56ce-bf0b-4b8f-92cd-69fa87168ebc.jpg)

**Comment by stevejburge** [comment]
@olatechpro Yes, this is similar to what we did on the Capabilities screen. Capabilities will now remember your choices when you reload the page

**Comment by olatechpro** [comment]
@stevejburge , can you link the pages here, in the screenshot i shared above in content overview screen, last used filters are remembered. @stevejburge

**Comment by stevejburge** [comment]
Ah, thanks. Maybe this was solved in a prior release and can be closed

**Comment by olatechpro** [comment]
I think so.
