### ISSUE TITLE
Improve date handling for custom statuses

### ISSUE THREAD

**Issue by Absotively** [publishpress/PublishPress#741]
I looked into the date handling issue in #546 because I would like backdated posts to work. I noticed that WordPress only changes the date to the present date on posts with statuses that have `date_floating` false or not set. This was added in 5.3, which is the same version in which the problem appeared.

I have tested adding `'date_floating' => false,` to `$postStatusArgs` in `register_custom_statuses` and removing or adding version checks to the other date fixing code in custom_statuses. This appeared to me to fix both the problems reported in #546 and the post backdating problems caused by the workaround for #546.

I can submit a PR if you like. I haven't tested my changes with older WordPress versions, though.

**Comment by andergmartins** [comment]
Hi @Absotively, thank you for your contribution.

The idea makes sense for sure, but I wasn't able to test it yet.
If you can submit a PR that would be really appreciated.

Thanks

**Comment by andergmartins** [comment]
Just merged the PR. Thanks for the contribution.
