### ISSUE TITLE
Publishpress causes a fatal error in Wordpress

### ISSUE THREAD

**Issue by leonvdz** [publishpress/PublishPress#767]
On www.jazzcape.nl I use publishpress and since this morning without any warning, our site crashes.
In Wordpress I see following information after entering in recovery mode:
 Deze plugin kon niet juist geladen worden en is gepauzeerd tijdens herstel mode.

Een fout van het type E_ERROR werd veroorzaakt op regelnummer 415 van het bestand /var/www/vhosts/jazzcape.nl/httpdocs/wp-content/plugins/publishpress/modules/editorial-metadata/editorial-metadata.php. Foutmelding: Uncaught Error: Call to a member function add_cap() on null in /var/www/vhosts/jazzcape.nl/httpdocs/wp-content/plugins/publishpress/modules/editorial-metadata/editorial-metadata.php:415 Stack trace: #0 /var/www/vhosts/jazzcape.nl/httpdocs/wp-content/plugins/publishpress/modules/editorial-metadata/editorial-metadata.php(227): PP_Editorial_Metadata->setDefaultCapabilities() #1 /var/www/vhosts/jazzcape.nl/httpdocs/wp-content/plugins/publishpress/publishpress.php(463): PP_Editorial_Metadata->upgrade('3.0.1') #2 /var/www/vhosts/jazzcape.nl/httpdocs/wp-includes/class-wp-hook.php(287): publishpress->action_ini_for_admin('') #3 /var/www/vhosts/jazzcape.nl/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #4 /var/www/vhosts/jazzcape.nl/httpdocs/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #5 /var/www/vhosts/jazzcape.nl/httpdocs/wp-settings.php(557): do_action('init') #6 /var/www/vhosts/jazzcape.nl/httpdocs/wp-config.php(167): require_once('/var/www/vhosts...') #7 /var/www/vhost

**Comment by pteranodog** [comment]
I am having this issue as well, beginning immediately after the auto-update to 3.0.2 that took place a few days ago. I deactivated all of my plugins via the command line and turned them all back on one by one. When I clicked "activate" for PublishPress, I was immediately shown the prompt stating "A fatal error has occurred." No other plugins show this error when activated.

**Comment by andergmartins** [comment]
Thank you for reporting the issue. This happens when one of the roles `administrator`, `editor` or `author` is missed on the site. The code should check that before trying to use the role.

**Comment by agata2011** [comment]
Hi,
An hour ago I tried to instal PublishPress on my freesite hosted at WordPress.com and this is what I've got:
 Fatal error: Call to undefined function wp_doing_cron() in /home/virtualki/170248/wp-content/plugins/publishpress/modules/notifications-log/notifications-log.php on line 680

Now I can't enter Cockpit or anything

what to do?
