### ISSUE TITLE
There was a critical error due to the latest update of PublishPress

### ISSUE THREAD

**Issue by euroblonde** [publishpress/PublishPress#774]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

Couldn't find a similar issue in recent posts. Apologies if it already appears.

## Current Behavior

My website was down due to the latest update in Publish Press.

When accessing the site the error message was the following:

"Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5".

There has been a critical error on this website. Please check your site admin email inbox for instructions."

## Possible Solution

I desactivated the plugin. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 3.0.3
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): MacOS Big Sur
* Link to your project:

**Comment by stevejburge** [comment]
@euroblonde Thanks. @andergmartins is working on a fix for this that should be released this week

**Comment by andergmartins** [comment]
@euroblonde thanks, I just released a new package addressing this bug.

**Comment by euroblonde** [comment]
Great! Many thanks.
