### ISSUE TITLE
PPRESS-260 ⁃ Content Checklist add-on: check for Yoast SEO meta desc and focus keyword

### ISSUE THREAD

**Issue by jphorn** [publishpress/PublishPress#81]
In your upcoming features you're mentioning [some ideas](https://pressshack.com/addons/content-checklist/) for the Content Checklist, of which some for Yoast SEO. I hope you'll consider adding two requirements which are already available in the plugin [Requirements Checklist](https://wordpress.org/plugins/post-type-requirements-checklist/#developers) which we currently use:

- [ ] Require Meta Description
- [ ] Require Focus Keyword

![screen-shot-2017-09-22-12-29-11](https://user-images.githubusercontent.com/478156/30740729-72efb9fa-9f92-11e7-98cf-83c75803ff14.png)

Also; I hope the 'Get the green checkmark for Yoast SEO' is optional, since even team Yoast state it's [not always worth pursuing](https://yoast.com/want-green-bullet-wp-seo/).

I really like the other feature ideas and look forward to their implementation.

**Comment by stevejburge** [comment]
Thumbs up from me on this one. We should start adding integrations for the checklist, and Yoast is by the most popular request

**Comment by jphorn** [comment]
Was this ever considered? I was looking through the changelog and noticed it isn't a requirement option yet. We really think this is important in our workflow and I prefer to use the PublishPress add-on instead of our current plugin ([Requirements Checklist](https://wordpress.org/plugins/post-type-requirements-checklist/#developers))

**Comment by stevejburge** [comment]
@jphorn Thanks - sorry, not yet. We plan on big improvements to our Github repos in the next month or so. Content Checklist will get it's own public repo with it's own issues
