### ISSUE TITLE
Integration problem with PublishPress Authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#913]
<img width="523" alt="Screen Shot 2021-07-23 at 10 20 39 AM" src="https://user-images.githubusercontent.com/3868028/126796822-31e17abe-b082-4952-87f1-390c14763b72.png">

**Comment by andergmartins** [comment]
@stevejburge This happens when the selected author is mapped to a user that is an author but doesn't have post edit permission, like a "subscriber".

**Comment by stevejburge** [comment]
@andergmartins Yes, that seems like best solution. Only show users who have edit_posts
