### ISSUE TITLE
Fix calendar time picker am/pm selection

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#914]
<img width="464" alt="Screen Shot 2021-07-23 at 10 25 59 AM" src="https://user-images.githubusercontent.com/3868028/126796881-c4ff8345-9196-4c78-bcd2-5ad680ddc7ba.png">

**Comment by olatechpro** [comment]
@stevejburge does your calendar still shows seconds? Mine doesn't which i believe may have been removed for a purpose.

Can you check?

**Comment by stevejburge** [comment]
@olatechpro yes, seconds don't seem to be supported. I can't enter them in the settings either:
<img width="425" alt="Screen Shot 2022-08-12 at 12 01 41 PM" src="https://user-images.githubusercontent.com/3868028/184396220-aeab0fa7-92c1-4b2f-9fa2-53d215c7cbd5.png">

Should we disable seconds for now, primarily in this settings box?

**Comment by olatechpro** [comment]
@stevejburge I mean it’s no longer on the calendar screen as initial screenshot.

So, i’m asking you to confirm if it’s just me or it changes already.

**Comment by stevejburge** [comment]
No, it's not just you :)

Let's remove for now
