### ISSUE TITLE
"Save Draft" button has gone with PublishPress active

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#967]
<img width="1163" alt="Screen Shot 2021-10-28 at 2 42 08 PM" src="https://user-images.githubusercontent.com/3868028/139316430-9460daae-fc10-4c99-bcc8-c058f996bf46.png">

**Comment by andergmartins** [comment]
@stevejburge Sorry, I can't replicate this one. Please, do we have more information about how to reproduce the issue? Testing on v3.6.2

**Comment by stevejburge** [comment]
@andergmartins Can you check our site at PublishPress.com for an example?

**Comment by stevejburge** [comment]
@andergmartins From a customer:

> Updating from 3.4.0 to 3.6.0 makes only "draft" status available. Updating from 3.4.0 to 3.6.2 shows all custom statuses, but "draft" is chosen by default, breaking our current workflow.
> 
> Disabling all other plugins results in same behavior.

**Comment by andergmartins** [comment]
> @andergmartins From a customer:
> 
> > Updating from 3.4.0 to 3.6.0 makes only "draft" status available. Updating from 3.4.0 to 3.6.2 shows all custom statuses, but "draft" is chosen by default, breaking our current workflow.
> > Disabling all other plugins results in same behavior.

@stevejburge I think that is working that way because we removed the feature that allowed users to customize the default status, #621. Do you think I should look for another approach to restore that feature?

**Comment by stevejburge** [comment]
@andergmartins Maybe we're mixing up issues on this ticket, but let's start with a new install.

A brand new install with just PublishPress, leads to a missing "Save Draft" link. The only thing you do with the post is publish it


![Screen Shot 2021-11-04 at 1 11 57 PM](https://user-images.githubusercontent.com/3868028/140387049-bc266acc-c2cc-4be0-b186-c923f793b05f.png)

**Comment by andergmartins** [comment]
Yeah, sorry. I mixed 2 issues here. Thanks, I will check again on a fresh install

**Comment by stevejburge** [comment]
@andergmartins. Sorry, this may have been me.

My original issue and the customers issue may not be connected

**Comment by andergmartins** [comment]
Just some details I found about this bug:

This is a browser-specific bug. I can only replicate it on Firefox.
The `Save as draft` button tab, on Firefox, is missing the attribute `aria-label`, used to print the text in the button. 

The button is there, but missing the text.
