### ISSUE TITLE
Add a "Content Overview" settings tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#971]
Let's have a new area to customize the Content Overview

![Screen Shot 2021-11-17 at 9 39 08 AM](https://user-images.githubusercontent.com/3868028/142221179-58e48818-2f90-4c56-8bcc-c4c102a744f9.png)

**Comment by olatechpro** [comment]
What settings are we moving to this new tab ? I'm completely new to this plugin and a direction will help @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Just the Post Types setting in the image above, plus also taxonomies https://github.com/publishpress/PublishPress/issues/970

**Comment by olatechpro** [comment]
Okay, got it
