### ISSUE TITLE
Deprecated: Required parameter $lineno 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#989]
This is on PHP 8
Deprecated: Required parameter $lineno follows optional parameter $only in /plugins/publishpress-pro/vendor/twig/twig/src/Node/IncludeNode.php on line 25

<img width="1080" alt="Screen Shot 2022-01-07 at 3 04 59 PM" src="https://user-images.githubusercontent.com/3868028/148600796-8a181d54-58c1-48ee-9bde-c3003f676b7a.png">

**Comment by olatechpro** [comment]
@stevejburge do you need me to check the https://github.com/publishpress/EDD-SL-Plugin-Updater since it's responsible for the issue?

**Comment by andergmartins** [comment]
We are removing Twig on #1125
